### PR TITLE
ENH: adds QIIME 1 core microbiome computation

### PR DESCRIPTION
**Pull request by gregcaporaso**
Example QZVs based on moving pics tutorial data:

[All samples](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdl.dropbox.com%2Fs%2Fxrwx0kjnda7c296%2Fcore.qzv%3Fdl%3D1)
[Gut-only samples (i.e., using `--p-where`)](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdl.dropbox.com%2Fs%2F684ypykeiwo84nu%2Fcore-gut-only.qzv%3Fdl%3D1)

~These need to be q2-templated, either now or in the future. If now, it would be helpful to pair-program that with someone.~

### CODE REVIEW

**Comment by thermokarst** [comment]
@gregcaporaso, I would be happy to pair-program q2templates-support with you, or, I could add a commit to this PR with the changes --- your call! I think we could have it knocked out in under 30 min if we worked on it together. q2templates could come in a second PR, as you mentioned, so I guess it depends on what the priorities are right now.

**Comment by gregcaporaso** [comment]
This is ready for final review.

**Comment by jairideout** [comment]
I'm porting this functionality to q2-feature-table with the visualizer name `core-features`. Will close this PR in favor of the ported PR when it's ready (wrapping up some final loose ends right now).

**Comment by jairideout** [comment]
Closing in favor of https://github.com/qiime2/q2-feature-table/pull/127

**Pull request closed without merging**
