### PR TITLE
Transition alpha_phylogenetic_alt to alpha_phylogenetic

### PR DESCRIPTION
**Pull request by gwarmstrong**
This PR is to transition the `alpha_phylogenetic_alt` method to `alpha_phylogenetic` as the main method for computing Faith's PD with `q2-diversity`. As a reminder, the implementation for the current `alpha_phylogenetic_alt` yields speed improvements and a memory reduction of several orders of magnitude. See [here](https://github.com/biocore/unifrac/pull/65) for more details.

### CODE REVIEW

**Comment by thermokarst** [comment]
Hey @gwarmstrong, this'll be great to get into the next release. Looks like the test suite is failing - I'll leave this for you to investigate, but, if you need a hand just ping us here. Thanks!

**Comment by gwarmstrong** [comment]
@thermokarst this fell off the radar for a little bit. Thanks for the ping!

**Comment by gwarmstrong** [comment]
So one of the issues with my addition is that `alpha_rarefaction` takes a `biom.Table` and the alternative`alpha_phylogenetic` takes a `BIOMV210Format`. I think the appropriate band-aid is to transform the table into the appropriate type right before plugging it into `alpha_phylogenetic`.

Can you recommend the best way to access the `biom.Table` -> `BIOMV210Format` transformer?

**Comment by gwarmstrong** [comment]
It looks like I may be able to use this?
`from qiime2.plugin.util import transform`

**Comment by thermokarst** [comment]
> It looks like I may be able to use this?
> `from qiime2.plugin.util import transform`

Yes indeed! That util is the best way to manually invoke a transformation.

**Comment by gwarmstrong** [comment]
By the way, this is passing the test suite now. It is just failing on coverage, since there were already a few uncovered lines in beta and I decreased the total line count.

**Comment by thermokarst** [comment]
Sweet, thanks! Coverage measurements can be so silly sometimes - I'll pop this over into the "Review" column - thanks!

**Comment by gwarmstrong** [comment]
@thermokarst your changes look good to me! Preserving the old behavior makes sense.

I also made changes to `alpha_rarefaction` [here](https://github.com/qiime2/q2-diversity/pull/272/files#diff-938bddf064046a59925f75268cfd23b7R298-R367), should we add an `alpha_rarefaction_old` to mirror `alpha_phylogenetic_old`?

Thanks!

**Comment by thermokarst** [comment]
> should we add an alpha_rarefaction_old to mirror alpha_phylogenetic_old

Hmm... I think I'm fine leaving out any kind of escape hatch for the alpha rarefaction viz, since it is diagnostic in nature.

**Pull request merged**
