### PR TITLE
ENH/API: support coloring Mantel scatters

### PR DESCRIPTION
**Pull request by wasade**
This pull request introduces a means to color the Mantel scatter plots by a categorical variable, which can help emphasize structure in the plot. An example is attached
Screen Shot 2021-10-27 at 4 12 58 PM

### CODE REVIEW

**Comment by lizgehret** [comment]
Closed and re-opened to trigger CI workflow

**Comment by lizgehret** [comment]
> That's a much prettier output! Also, the error you're getting confused me for a few minutes:
> 
> ```
> TypeError: Parameter 'metadata' received 'Metadata' as an argument, which is incompatible with parameter type: MetadataColumn[Categorical]
> ```
> 
> But it's complaining about a python string `"Metadata"` which is the default label for beta_correlation (`label1`). I think if you update that pipeline (probably with keywords) the tests should pass.

Hey @wasade I took a quick look over this PR and re-ran ci and we're still getting the same test failures that @ebolyen mentioned above. Our PR cutoff for the 2022.8 release was technically yesterday, so unless you have something ready to go here to address these failures before EOD we'll have to hold off on this one until the 2022.11 release.

**Comment by wasade** [comment]
TBH its been so long I don't recall what this really does. I'm on leave for
a few more weeks, it would be okay to close this.

**Comment by lizgehret** [comment]
Sounds good @wasade, I'll go ahead and close it! We can always re-open if/when you have bandwidth and want to fix up these test failures. Enjoy your time off! 🙂

**Pull request closed without merging**
