### PR TITLE
TST: adds coverage testing and reporting to Travis CI

### PR DESCRIPTION
**Pull request by gregcaporaso**

### CODE REVIEW

**Comment by jairideout** [comment]
Adding *do not merge* label until the `pip install -e .` issue is sorted out.

**Comment by gregcaporaso** [comment]
This latest commit seems to fix the issue (locally at least - travis doesn't seem to have started yet). The issue was that the `tests` directory was missing a ``__init__.py`` file, and this seems to be required for `py.test --cov` to function correctly.

**Comment by gregcaporaso** [comment]
Travis/Coverage are passing now, and the coverage report is correct on coveralls.

**Comment by jairideout** [comment]
Thanks @gregcaporaso! The missing `__init__.py` would have affected `nosetests` as well. It's possible these tests weren't being executed before, but I haven't confirmed that. Thanks for fixing!

**Pull request merged**
